package com.t3g.cookbooks.gui.admin.catalogue;

/**
*
* @author Fabrizio
*/
public class Register extends javax.swing.JFrame {

   /**
    * Creates new form Register
    */
   public Register() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

       jInternalFrame1 = new javax.swing.JInternalFrame();
       jPanel1 = new javax.swing.JPanel();
       lblPrincipalpicture = new javax.swing.JLabel();
       txtUser = new javax.swing.JTextField();
       btnLogin = new javax.swing.JButton();
       lblForgotPass = new javax.swing.JLabel();
       txtPassword = new javax.swing.JPasswordField();
       txtSearch = new javax.swing.JTextField();
       btnSearch = new javax.swing.JButton();
       txtHome = new javax.swing.JLabel();
       txtOrder = new javax.swing.JLabel();
       txtHelp = new javax.swing.JLabel();
       txtContac = new javax.swing.JLabel();
       txtRegister = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setPreferredSize(new java.awt.Dimension(800, 600));

       jInternalFrame1.setBackground(new java.awt.Color(153, 153, 255));
       jInternalFrame1.setForeground(new java.awt.Color(153, 153, 255));
       jInternalFrame1.setVisible(true);

       jPanel1.setBackground(new java.awt.Color(153, 153, 255));

       lblPrincipalpicture.setIcon(new javax.swing.ImageIcon("D:\\Facultad - Ingeniería en Computación\\Ingeniería de software\\Proyecto\\cookbookLogoReducido.png")); // NOI18N
       lblPrincipalpicture.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               lblPrincipalpictureMousePressed(evt);
           }
       });

       txtUser.setText("Usuario");

       btnLogin.setText("Ingresar");
       btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               btnLoginMouseClicked(evt);
           }
           public void mousePressed(java.awt.event.MouseEvent evt) {
               btnLoginMousePressed(evt);
           }
       });

       lblForgotPass.setBackground(new java.awt.Color(51, 51, 255));
       lblForgotPass.setForeground(new java.awt.Color(51, 51, 255));
       lblForgotPass.setText("Olvide mi contraseña");
       lblForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               lblForgotPassMouseClicked(evt);
           }
           public void mousePressed(java.awt.event.MouseEvent evt) {
               lblForgotPassMousePressed(evt);
           }
       });

       txtPassword.setText("Contraseña");
       txtPassword.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtPasswordActionPerformed(evt);
           }
       });

       txtSearch.setText("Búsqueda");
       txtSearch.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtSearchActionPerformed(evt);
           }
       });

       btnSearch.setText("Buscar");
       btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               btnSearchMousePressed(evt);
           }
       });

       txtHome.setText("Principal");

       txtOrder.setForeground(new java.awt.Color(51, 51, 255));
       txtOrder.setText("Pedidos");
       txtOrder.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               txtOrderMousePressed(evt);
           }
       });

       txtHelp.setForeground(new java.awt.Color(51, 51, 255));
       txtHelp.setText("Ayuda");
       txtHelp.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               txtHelpMousePressed(evt);
           }
       });

       txtContac.setForeground(new java.awt.Color(51, 51, 255));
       txtContac.setText("Contacto");
       txtContac.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               txtContacMousePressed(evt);
           }
       });

       txtRegister.setForeground(new java.awt.Color(51, 51, 255));
       txtRegister.setText("Registrarse");
       txtRegister.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mousePressed(java.awt.event.MouseEvent evt) {
               txtRegisterMousePressed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(btnSearch)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                       .addComponent(txtHome)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(txtOrder)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(txtHelp)
                       .addGap(10, 10, 10)
                       .addComponent(txtContac)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(txtRegister))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(lblPrincipalpicture)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addComponent(lblForgotPass)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addComponent(btnLogin))
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
               .addGap(23, 23, 23))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(btnLogin)
                   .addComponent(lblForgotPass))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addComponent(lblPrincipalpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(btnSearch)
                   .addComponent(txtHome)
                   .addComponent(txtOrder)
                   .addComponent(txtHelp)
                   .addComponent(txtContac)
                   .addComponent(txtRegister))
               .addContainerGap())
       );

       javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
       jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
       jInternalFrame1Layout.setHorizontalGroup(
           jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       jInternalFrame1Layout.setVerticalGroup(
           jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jInternalFrame1Layout.createSequentialGroup()
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 678, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jInternalFrame1)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jInternalFrame1)
       );

       pack();
   }// </editor-fold>

   private void lblForgotPassMouseClicked(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
   }

   private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here: 
   }

   private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {
       // TODO add your handling code here:
   }

   private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para ingresar a la página, y loguearse. Abre pantalla home pero ya logueado.
   }

   private void lblForgotPassMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para recuperar contraseña, abre pantalla de "olvide contraseña"
   }

   private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para realizar una búsqueda, en txtSearch esta lo que buscamos
   }

   private void lblPrincipalpictureMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
      // TODO Evento para ir a la interfaz principal. Al hacer click en la imágen "cookbook" voy al inicio.
   }

   private void txtRegisterMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para ir a la interfaz de registro
   }

   private void txtContacMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para ir a la interfaz de contacto
   }

   private void txtHelpMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para ir a la interfaz de ayuda
   }

   private void txtOrderMousePressed(java.awt.event.MouseEvent evt) {
       // TODO add your handling code here:
       // TODO Evento para ir a la interfaz de pedidos
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new Register().setVisible(true);
           }
       });
   }
   // Variables declaration - do not modify
   private javax.swing.JButton btnLogin;
   private javax.swing.JButton btnSearch;
   private javax.swing.JInternalFrame jInternalFrame1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JLabel lblForgotPass;
   private javax.swing.JLabel lblPrincipalpicture;
   private javax.swing.JLabel txtContac;
   private javax.swing.JLabel txtHelp;
   private javax.swing.JLabel txtHome;
   private javax.swing.JLabel txtOrder;
   private javax.swing.JPasswordField txtPassword;
   private javax.swing.JLabel txtRegister;
   private javax.swing.JTextField txtSearch;
   private javax.swing.JTextField txtUser;
   // End of variables declaration
}

